[versions]
spock = "2.4-groovy-4.0"

[plugins]
integration-test = { id = "com.coditory.integration-test", version = "2.2.5" }
test-logger = { id = "com.adarshr.test-logger", version = "4.0.0" }
axion-release = { id = "pl.allegro.tech.build.axion-release", version = "1.21.0" }

[libraries]
spock-core = { group = "org.spockframework", name = "spock-core", version.ref = "spock" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }